"""
Unit tests for the DOCX parser.

Tests verify:
1. Comment extraction from comments.xml
2. Anchor text extraction via commentRangeStart/End
3. Clause expansion to smallest numbered subclause (12.3(a) level)
4. Tracked-change stripping (w:del ignored)
5. Thread concatenation

Uses tests/fixtures/sample.docx (generated by create_fixtures.py).
"""

import os
import sys
from pathlib import Path

import pytest

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _ensure_fixture():
    """Create fixture if it doesn't exist."""
    docx_path = FIXTURES_DIR / "sample.docx"
    if not docx_path.exists():
        from tests.create_fixtures import create_sample_docx
        create_sample_docx()
    return docx_path


class TestDocxParser:
    def test_parse_returns_results(self):
        """Parser should return at least one ExtractedClause."""
        from app.parsers.docx_parser import parse_docx

        docx_path = _ensure_fixture()
        file_bytes = docx_path.read_bytes()
        results = parse_docx(file_bytes)
        assert len(results) > 0, "Expected at least one extracted clause"

    def test_anchor_text_extracted(self):
        """Anchor text should contain the highlighted phrase."""
        from app.parsers.docx_parser import parse_docx

        docx_path = _ensure_fixture()
        file_bytes = docx_path.read_bytes()
        results = parse_docx(file_bytes)

        anchor_texts = [r.anchor_text for r in results]
        # The comment is on "liable for"
        assert any("liable for" in t for t in anchor_texts), (
            f"Expected 'liable for' in anchor texts, got: {anchor_texts}"
        )

    def test_clause_expansion_to_numbered_subclause(self):
        """Clause should expand to the 12.3(a) numbered subclause, not the whole section."""
        from app.parsers.docx_parser import parse_docx

        docx_path = _ensure_fixture()
        file_bytes = docx_path.read_bytes()
        results = parse_docx(file_bytes)

        # Find the result with "liable for" anchor
        matching = [r for r in results if "liable for" in r.anchor_text]
        assert matching, "No result found for 'liable for' anchor"

        result = matching[0]
        # Clause number should be the specific subclause 12.3(a)
        assert result.clause_number is not None, "Expected a clause_number"
        assert "12.3" in result.clause_number or "12" in result.clause_number, (
            f"Expected numbered subclause, got: {result.clause_number}"
        )
        # Expansion method should be numbered_subclause, not paragraph
        assert result.expansion_method in ("numbered_subclause", "boundary_merge"), (
            f"Expected numbered expansion, got: {result.expansion_method}"
        )

    def test_comment_text_extracted(self):
        """Comment text should be extracted from comments.xml."""
        from app.parsers.docx_parser import parse_docx

        docx_path = _ensure_fixture()
        file_bytes = docx_path.read_bytes()
        results = parse_docx(file_bytes)

        all_comments = [c for r in results for c in r.comment_texts]
        assert any("liable" in c.lower() or "broad" in c.lower() or "cap" in c.lower() for c in all_comments), (
            f"Expected comment text about liability, got: {all_comments}"
        )

    def test_comment_author_extracted(self):
        """Comment author should be extracted."""
        from app.parsers.docx_parser import parse_docx

        docx_path = _ensure_fixture()
        file_bytes = docx_path.read_bytes()
        results = parse_docx(file_bytes)

        authors = [a for r in results for a in r.comment_authors if a]
        assert "Legal Reviewer" in authors, (
            f"Expected 'Legal Reviewer' in authors, got: {authors}"
        )

    def test_high_confidence_for_numbered_clause(self):
        """Numbered subclause expansion should give high confidence."""
        from app.parsers.docx_parser import parse_docx

        docx_path = _ensure_fixture()
        file_bytes = docx_path.read_bytes()
        results = parse_docx(file_bytes)

        numbered_results = [r for r in results if r.clause_number is not None]
        for r in numbered_results:
            assert r.confidence in ("high", "medium"), (
                f"Expected high/medium confidence for numbered clause, got: {r.confidence}"
            )

    def test_clause_text_contains_subclause_content(self):
        """The extracted clause_text should contain the full subclause body."""
        from app.parsers.docx_parser import parse_docx

        docx_path = _ensure_fixture()
        file_bytes = docx_path.read_bytes()
        results = parse_docx(file_bytes)

        matching = [r for r in results if "liable for" in r.anchor_text]
        if matching:
            clause_text = matching[0].clause_text
            assert "breach" in clause_text.lower() or "liable" in clause_text.lower(), (
                f"Expected clause body text, got: {clause_text[:200]}"
            )


class TestClausePatterns:
    def test_extract_numbered_patterns(self):
        """Clause number extraction should handle all common patterns."""
        from app.parsers.clause_patterns import extract_clause_number

        test_cases = [
            ("12.3(a) Some text", "12.3(a)"),
            ("12.3.1 Some text", "12.3.1"),
            ("12.3 Some text", "12.3"),
            ("12. Some text", "12."),
            ("(a) Some text", "(a)"),
            ("Section 5. Some text", "Section 5."),
            ("No number here", None),
        ]
        for text, expected in test_cases:
            result = extract_clause_number(text)
            if expected is None:
                assert result is None, f"Expected None for '{text}', got: {result}"
            else:
                assert result is not None, f"Expected '{expected}' for '{text}', got None"
                assert expected.rstrip(".") in result or result.rstrip(".") in expected, (
                    f"Expected '{expected}' for '{text}', got: {result}"
                )

    def test_specificity_scoring(self):
        """More specific clause numbers should have higher scores."""
        from app.parsers.clause_patterns import specificity_score

        assert specificity_score("12.3(a)") > specificity_score("12.3")
        assert specificity_score("12.3") > specificity_score("12.")
        assert specificity_score("12.") > specificity_score(None)
        assert specificity_score("12.3.1(a)") >= specificity_score("12.3(a)")
