"""
Unit tests for the PDF parser.

Tests verify:
1. Annotation extraction (Highlight annotations)
2. Anchor text extraction from quadpoints
3. Clause expansion to numbered subclause
4. FreeText nearest-block fallback
5. OCR trigger detection

Uses tests/fixtures/sample.pdf (generated by create_fixtures.py).
"""

import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _ensure_pdf_fixture():
    """Create PDF fixture if it doesn't exist."""
    pdf_path = FIXTURES_DIR / "sample.pdf"
    if not pdf_path.exists():
        from tests.create_fixtures import create_sample_pdf
        create_sample_pdf()
    return pdf_path


class TestPdfParser:
    def test_parse_returns_results(self):
        """Parser should return at least one ExtractedClause."""
        pytest.importorskip("fitz", reason="PyMuPDF required for PDF tests")
        from app.parsers.pdf_parser import parse_pdf

        pdf_path = _ensure_pdf_fixture()
        file_bytes = pdf_path.read_bytes()
        results = parse_pdf(file_bytes)
        assert len(results) > 0, "Expected at least one extracted clause from PDF"

    def test_anchor_text_extracted(self):
        """Highlighted text should be extracted as anchor_text."""
        pytest.importorskip("fitz", reason="PyMuPDF required for PDF tests")
        from app.parsers.pdf_parser import parse_pdf

        pdf_path = _ensure_pdf_fixture()
        file_bytes = pdf_path.read_bytes()
        results = parse_pdf(file_bytes)

        anchor_texts = " ".join(r.anchor_text for r in results)
        # The highlighted text is "limit its liability"
        assert "limit" in anchor_texts.lower() or "liability" in anchor_texts.lower(), (
            f"Expected highlighted text in anchors, got: {anchor_texts[:200]}"
        )

    def test_comment_text_from_annotation(self):
        """Annotation contents should be extracted as comment text."""
        pytest.importorskip("fitz", reason="PyMuPDF required for PDF tests")
        from app.parsers.pdf_parser import parse_pdf

        pdf_path = _ensure_pdf_fixture()
        file_bytes = pdf_path.read_bytes()
        results = parse_pdf(file_bytes)

        all_comments = " ".join(c for r in results for c in r.comment_texts)
        assert "unacceptable" in all_comments.lower() or "limitation" in all_comments.lower(), (
            f"Expected annotation comment text, got: {all_comments[:200]}"
        )

    def test_clause_expansion_near_annotation(self):
        """Expansion should find the numbered clause near the annotation."""
        pytest.importorskip("fitz", reason="PyMuPDF required for PDF tests")
        from app.parsers.pdf_parser import parse_pdf

        pdf_path = _ensure_pdf_fixture()
        file_bytes = pdf_path.read_bytes()
        results = parse_pdf(file_bytes)

        # Should find clause with some numbering
        assert len(results) > 0
        r = results[0]
        # Clause text should contain content around the annotation
        assert len(r.clause_text) > 10, "Clause text too short"

    def test_page_number_stored(self):
        """Page number should be recorded for PDF clauses."""
        pytest.importorskip("fitz", reason="PyMuPDF required for PDF tests")
        from app.parsers.pdf_parser import parse_pdf

        pdf_path = _ensure_pdf_fixture()
        file_bytes = pdf_path.read_bytes()
        results = parse_pdf(file_bytes)

        for r in results:
            assert r.page_number is not None, "Expected page_number to be set"
            assert r.page_number >= 0

    def test_bbox_stored_as_list(self):
        """Bbox should be stored as a list of {page, rect} dicts."""
        pytest.importorskip("fitz", reason="PyMuPDF required for PDF tests")
        from app.parsers.pdf_parser import parse_pdf

        pdf_path = _ensure_pdf_fixture()
        file_bytes = pdf_path.read_bytes()
        results = parse_pdf(file_bytes)

        for r in results:
            if r.bbox:
                assert isinstance(r.bbox, list), "Bbox should be a list"
                assert len(r.bbox) > 0
                first = r.bbox[0]
                assert "page" in first, "Bbox entry should have 'page' key"
                assert "rect" in first, "Bbox entry should have 'rect' key"
                assert len(first["rect"]) == 4, "Rect should have 4 coordinates"


class TestOcrUtils:
    def test_is_garbage_text_empty(self):
        """Empty text should be detected as garbage."""
        from app.parsers.ocr import is_garbage_text

        assert is_garbage_text("") is True
        assert is_garbage_text("   ") is True

    def test_is_garbage_text_low_alpha_ratio(self):
        """Text with very low alphanumeric ratio should be garbage."""
        from app.parsers.ocr import is_garbage_text

        assert is_garbage_text("!@#$%^&*()") is True
        assert is_garbage_text("????.....!!!") is True

    def test_is_garbage_text_normal(self):
        """Normal legal text should not be garbage."""
        from app.parsers.ocr import is_garbage_text

        assert is_garbage_text("The Vendor shall not limit its liability") is False
        assert is_garbage_text("12.3(a) Indemnification clause") is False
